spring:
  application:
    name: kafka-listener
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: box-engine-consumer
      auto-offset-reset: earliest
#      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
#        schema.registry.url: ${SCHEMA_REGISTRY_URL}
#        specific.avro.reader: true   # se vocÃª quer SpecificRecord (classes geradas)
        max.poll.records: 50
        max.poll.interval.ms: 300000
        session.timeout.ms: 15000
        heartbeat.interval.ms: 5000

    listener:
      ack-mode: manual
      type: single
      missing-topics-fatal: false
      concurrency: 10
      observation-enabled: true
    template:
      observation-enabled: true

